Meteo/Models/ErrorViewModel.cs
namespace MeteoWww.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Meteo/Models/HomeModel.cs
using System.Collections.Generic;
using MeteoPortable.Data;

namespace MeteoWww.Models
{
    public class HomeModel
    {
        public List<Measurement> Measurements { get; set; } = new List<Measurement>();
        public Measurement Measurement { get; set; }
    }
}

Meteo/Models/MeasurementsModel.cs
using System.Collections.Generic;
using MeteoPortable.Data;

namespace MeteoWww.Models
{
    public class MeasurementsModel
    {
        public List<ChartItem> ChartItems { get; set; } = new List<ChartItem>();
        public Measurement Measurement { get; set; }
    }
}

Meteo/Models/MeteoContext.cs
using MeteoPortable.Data;
using Microsoft.EntityFrameworkCore;

namespace Meteo.Models
{
    public class MeteoContext : DbContext
    {
        public MeteoContext(DbContextOptions<MeteoContext> options)
            : base(options)
        {
        }

        public DbSet<Measurement> Measurements { get; set; }
    }
}

Meteo/Models/SeedData.cs
using System;
using System.Linq;
using Meteo.Models;
using MeteoPortable.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MeteoWww.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new MeteoContext(serviceProvider.GetRequiredService<DbContextOptions<MeteoContext>>()))
            {
                if (context.Measurements.Any())
                {
                    return; // DB has been seeded
                }

                var mesasurForWeek = RandomMeasurements.GemerateForDays();
                context.Measurements.AddRange(mesasurForWeek);
                context.SaveChanges();
            }
        }
    }
}

Meteo/Models/SignalRHub.cs
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeteoWww.Models
{
    public class SignalRHub : Hub
    {
        public Task Send(string message)
        {
            return Clients.All.InvokeAsync("Send", message);
        }
    }
}

Meteo/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using MeteoWww.Models;
using MeteoWww.Services;
using Microsoft.AspNetCore.Mvc;

namespace Meteo.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMeasurementsService _measurementsService;
        private readonly IOneSignalService _oneSignalService;

        public HomeController(IMeasurementsService measurementsService, IOneSignalService oneSignalService)
        {
            _measurementsService = measurementsService;
            _oneSignalService = oneSignalService;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new HomeModel();
            var response = await _measurementsService.GetNewestMeasurementsAsync();
            if (response.Result.Success)
            {
                viewModel.Measurements = response.Measurements.ToList();
                viewModel.Measurement = viewModel.Measurements.FirstOrDefault();
            }
            return View(viewModel);
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GenerateSingleSeries()
        {
            await _measurementsService.GenerateSingleSeries();
            return new JsonResult("");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClearDatabase()
        {
            await _measurementsService.ClearDatabase();
            return new JsonResult("");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Generate3DaySeries()
        {
            await _measurementsService.Generate3DaySeries();
            return new JsonResult("");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SendPush()
        {
            _oneSignalService.SendTemperatureWarning(50);
            return new JsonResult("");
        }


        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Meteo/Controllers/MeasurementsApiController.cs
using System.Threading.Tasks;
using MeteoPortable.Data;
using MeteoWww.Services;
using Microsoft.AspNetCore.Mvc;

namespace MeteoWww.Controllers
{
    [Route("api/")]
    public class MeasurementsApiController : Controller
    {
        private readonly IMeasurementsService _measurementsService;

        public MeasurementsApiController(IMeasurementsService measurementsService)
        {
            _measurementsService = measurementsService;
        }

        // GET: api/Measurements/GetMeasurements
        [HttpGet("GetMeasurements")]
        public async Task<IActionResult> GetAllMeasurementsAsync()
        {
            var response = await _measurementsService.GetAllMeasurementsAsync();
            return new ObjectResult(response);
        }

        [HttpGet("GetWeeklyChart")]
        public async Task<IActionResult> GetWeeklyChartDataAsync()
        {
            var response = await _measurementsService.GetWeeklyRecordsAsync();
            return new ObjectResult(response);
        }

        [HttpGet("GetDailyChart")]
        public async Task<IActionResult> GetDailyChartDataAsync()
        {
            var response = await _measurementsService.GetDailyRecordsAsync();
            return new ObjectResult(response);
        }

        [HttpGet("GetLastRecordsChart")]
        public async Task<IActionResult> GetLastRecordsAsync([FromQuery] GetLastChartDataArgs args)
        {
            args.Count = args.Count != 0 ? args.Count : 20;
            var response = await _measurementsService.GetLastRecordsAsync(args.Count);
            return new ObjectResult(response);
        }

        // POST api/values
        [HttpPost("InsertMeasurements")]
        public async Task<IActionResult> Post([FromBody] MeasurementInsertBody data)
        {
            //_context.Measurements.AddRange(items);
            //_context.SaveChanges();
            var response = await _measurementsService.InsertMeasurementsAsync(data.Measurements.ToArray());

            return new ObjectResult(response);
        }
    }
}

Meteo/Controllers/MeasurementsController.cs
using System.Linq;
using System.Threading.Tasks;
using MeteoWww.Models;
using MeteoWww.Services;
using Microsoft.AspNetCore.Mvc;

namespace Meteo.Controllers
{
    public class MeasurementsController : Controller
    {
        private readonly IMeasurementsService _measurementsService;

        public MeasurementsController(IMeasurementsService measurementsService)
        {
            _measurementsService = measurementsService;
        }

        // GET: Measurements
        public async Task<IActionResult> Last20()
        {
            var response = await _measurementsService.GetLastRecordsAsync(20);
            if (response.Result.Success)
            {
                var measurementsModel = new MeasurementsModel();
                measurementsModel.ChartItems = response.ChartItems.ToList();
                return View(measurementsModel);
            }
            return NotFound();
        }

        public async Task<IActionResult> Weekly()
        {
            var response = await _measurementsService.GetWeeklyRecordsAsync();
            if (response.Result.Success)
            {
                var measurementsModel = new MeasurementsModel();
                measurementsModel.ChartItems = response.ChartItems.ToList();
                return View(measurementsModel);
            }
            return NotFound();
        }

        public async Task<IActionResult> Daily()
        {
            var response = await _measurementsService.GetDailyRecordsAsync();
            if (response.Result.Success)
            {
                var measurementsModel = new MeasurementsModel();
                measurementsModel.ChartItems = response.ChartItems.ToList();
                return View(measurementsModel);
            }
            return NotFound();
        }
    }
}

Meteo/Views/Home/Index.cshtml
@model HomeModel  ;
@{
    ViewData["Title"] = "Home Page";
}

<h1>Podgląd najnowszych pomiarów</h1>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Measurement.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Measurement.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Measurement.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Measurement.Type)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Measurements)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
        </tr>
    }
    </tbody>
</table>

<form method="post">
    <input type="button" value="Generuj 1 serię nowych pomiarów" class="btn btn-default" onclick="generateSingleSeries();"/>
</form>
<form method="post">
    <input type="button" value="Wyczyść bazę danych" class="btn btn-default" onclick="cleanDatabase();"/>
</form>
<form method="post">
    <input type="button" value="Wygeneruj losową baze dla 3 dni" class="btn btn-default" onclick="generate3DaySeries();"/>
</form>
<form method="post">
    <input type="button" value="Wyślij powiadomienie push" class="btn btn-default" onclick="sendPush();"/>
</form>

<script src="~/lib/jquery/dist/jquery.js"></script>

<script type="text/javascript">
    function generateSingleSeries() {
        $.ajax({
            type: "POST",
            url: 'Home/GenerateSingleSeries',
            contentType: "application/json; charset=utf-8",
            beforeSend: function(xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            dataType: "json"
        }).done(function(data) {
            console.log(data.result);
            location.reload(true);
        });
    }

    function cleanDatabase() {
        $.ajax({
            type: "POST",
            url: 'Home/ClearDatabase',
            contentType: "application/json; charset=utf-8",
            beforeSend: function(xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            dataType: "json"
        }).done(function(data) {
            console.log(data.result);
            location.reload(true);
        });
    }

    function generate3DaySeries() {
        $.ajax({
            type: "POST",
            url: 'Home/Generate3DaySeries',
            contentType: "application/json; charset=utf-8",
            beforeSend: function(xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            dataType: "json"
        }).done(function(data) {
            console.log(data.result);
            location.reload(true);
        });
    }

    function sendPush() {
        $.ajax({
            type: "POST",
            url: 'Home/SendPush',
            contentType: "application/json; charset=utf-8",
            beforeSend: function(xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            dataType: "json"
        }).done(function(data) {
            console.log(data.result);
        });
    }
</script>

Meteo/Views/Measurements/Daily.cshtml
@model MeasurementsModel

@{
    ViewData["Title"] = "Wyniki z ostatniego dnia";
}
<div>

    @foreach (var item in Model.ChartItems)
    {
        @(Html.Kendo().Chart()
              .Name(item.Title)
              .Title(item.Title)
              .Legend(legend => legend
                  .Position(ChartLegendPosition.Bottom)
              )
              .ChartArea(chartArea => chartArea
                  .Background("transparent")
              )
              .SeriesDefaults(seriesDefaults =>
                  seriesDefaults.Line().Style(ChartSeriesStyle.Smooth)
              )
              .Series(series =>
              {
                  for (var i = 0; i < item.Series.Count; i++)
                  {
                      series.Line(item.Series[i]).Name(item.SeriesTitle[i]);
                  }
              })
              .CategoryAxis(axis =>
                  axis.Categories(item.CategoryAxis)
                      .MajorGridLines(lines => lines.Visible(false))
              )
              .ValueAxis(axis => axis
                  .Numeric().Labels(labels => labels.Format("{0}"))
                  .Line(line => line.Visible(false))
                  .AxisCrossingValue(-10)
              )
              .Tooltip(tooltip => tooltip
                  .Visible(true)
                  .Format("{0}")
              )
              )
    }
</div>

Meteo/Views/Measurements/Last20.cshtml
@model MeasurementsModel

@{
    ViewData["Title"] = "Index";
}
<div>

    @foreach (var item in Model.ChartItems)
    {
        @(Html.Kendo().Chart()
              .Name(item.Title)
              .Title(item.Title)
              .Legend(legend => legend
                  .Position(ChartLegendPosition.Bottom)
              )
              .ChartArea(chartArea => chartArea
                  .Background("transparent")
              )
              .SeriesDefaults(seriesDefaults =>
                  seriesDefaults.Line().Style(ChartSeriesStyle.Smooth)
              )
              .Series(series =>
              {
                  for (var i = 0; i < item.Series.Count; i++)
                  {
                      series.Line(item.Series[i]).Name(item.SeriesTitle[i]);
                  }
              })
              .CategoryAxis(axis =>
                  axis.Categories(item.CategoryAxis)
                      .MajorGridLines(lines => lines.Visible(false))
              )
              .ValueAxis(axis => axis
                  .Numeric().Labels(labels => labels.Format("{0}"))
                  .Line(line => line.Visible(false))
                  .AxisCrossingValue(-10)
              )
              .Tooltip(tooltip => tooltip
                  .Visible(true)
                  .Format("{0}")
              )
              )
    }
</div>

Meteo/Views/Measurements/Weekly.cshtml
@model MeasurementsModel

@{
    ViewData["Title"] = "Wyniki z ostatniego tygoddnia";
}
<div>

    @foreach (var item in Model.ChartItems)
    {
        @(Html.Kendo().Chart()
              .Name(item.Title)
              .Title(item.Title)
              .Legend(legend => legend
                  .Position(ChartLegendPosition.Bottom)
              )
              .ChartArea(chartArea => chartArea
                  .Background("transparent")
              )
              .SeriesDefaults(seriesDefaults =>
                  seriesDefaults.Line().Style(ChartSeriesStyle.Smooth)
              )
              .Series(series =>
              {
                  for (var i = 0; i < item.Series.Count; i++)
                  {
                      series.Line(item.Series[i]).Name(item.SeriesTitle[i]);
                  }
              })
              .CategoryAxis(axis =>
                  axis.Categories(item.CategoryAxis)
                      .MajorGridLines(lines => lines.Visible(false))
              )
              .ValueAxis(axis => axis
                  .Numeric().Labels(labels => labels.Format("{0}"))
                  .Line(line => line.Visible(false))
                  .AxisCrossingValue(-10)
              )
              .Tooltip(tooltip => tooltip
                  .Visible(true)
                  .Format("{0}")
              )
              )
    }
</div>

Meteo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Meteo</title>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>


    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>

    @*KENDO*@
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/kendo-ui/styles/kendo.common-nova.min.css"/>
        <link rel="stylesheet" href="~/lib/kendo-ui/styles/kendo.nova.min.css"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet"
              href="https://kendo.cdn.telerik.com/2017.2.621/styles/kendo.common-nova.min.css"
              asp-fallback-href="~/lib/kendo-ui/styles/kendo.common-nova.min.css"
              asp-fallback-test-class="k-common-test-class"
              asp-fallback-test-property="opacity" asp-fallback-test-value="0"/>

        <link rel="stylesheet"
              href="https://kendo.cdn.telerik.com/2017.2.621/styles/kendo.nova.min.css"
              asp-fallback-href="~/lib/kendo-ui/styles/kendo.nova.min.css"
              asp-fallback-test-class="k-theme-test-class"
              asp-fallback-test-property="opacity" asp-fallback-test-value="0"/>
    </environment>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>

        @* Place Kendo UI scripts after jQuery *@
        <script src="~/lib/kendo-ui/js/kendo.all.min.js"></script>
        <script src="~/lib/kendo-ui/js/kendo.aspnetmvc.min.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>

        @*  Place Kendo UI scripts after jQuery *@
        <script src="https://kendo.cdn.telerik.com/2017.2.621/js/kendo.all.min.js"
                asp-fallback-src="~/lib/kendo-ui/js/kendo.all.min.js"
                asp-fallback-test="window.kendo">
        </script>
        <script src="https://kendo.cdn.telerik.com/2017.2.621/js/kendo.aspnetmvc.min.js"
                asp-fallback-src="~/lib/kendo-ui/js/kendo.aspnetmvc.min.js"
                asp-fallback-test="kendo.data.transports['aspnetmvc-ajax']">
        </script>
    </environment>
    @*END KENDO*@
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Meteo</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a asp-area="" asp-controller="Measurements" asp-action="Daily">Dzisiejsze pomiary</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Measurements" asp-action="Weekly">Pomiary z tygodnia</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Measurements" asp-action="Last20">20 ostatnich pomiarów</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; 2017 - Meteo</p>
    </footer>
</div>


@RenderSection("Scripts", false)
</body>
</html>